### ISSUE TITLE
Bug - Expected type ConstraintString

### ISSUE THREAD

**Issue by DawidNazarko** [alexanderVu/apollo-koa-constraint-directive#3]
Hi!

I have `@constraint(contains: "instagram", format: "uri")` and it works for package `apollo-server-constraint-directive` but not for this one because of the following error:

`Expected type ConstraintString. Must match ^[^.?+*|{}[\\]()\"\\\\#@&<>~]*$`

for input: `http://www.instagram.com/`

**Comment by alexanderVu** [comment]
Should be now fixed in version 1.2.0.

**Comment by DawidNazarko** [comment]
It works now, but there has emerged problem that I had with `apollo-server-constraint-directive` namely graphql playground doesn't work: `Server cannot be reached`.

**Comment by alexanderVu** [comment]
I'm not sure if I'm getting it right. 'apollo-koa-constraint-directive' is only required if you use 'koa' instead of 'apollo-server'. 'apollo-server-constraint-directive' is used when 'apollo-server' is used.

The error 'Server cannot be reached' can come from the fact that apollo (which is based on GraphQL) has internal differences functions like 'makeExecutableSchema', 'gql'. . . come from.
This is currently the reason why I created 'apollo-koa-constraint-directive' and 'apollo-server-constraint-directive'.
Hope this helps.

**Comment by DawidNazarko** [comment]
Well, I used wrong package at first. Now I use this one because I use koa and I have the same configuration as is in `Usage` docs and graphql playground doesn't work.

**Comment by alexanderVu** [comment]
Will test it with my koa playground.

**Comment by DawidNazarko** [comment]
Have you inspected the error?

**Comment by DawidNazarko** [comment]
@alexanderVu still graphql playground doesn't work

**Comment by alexanderVu** [comment]
@DawidNazarko The error should now be fixed. I wanted to add subscriptions also, but stuck on bug on apollo-server-koa module. The context argument on subscriptions is empty.

**Comment by DawidNazarko** [comment]
@alexanderVu great, are you going to fix the bug also in apollo-koa-constraint-directive, because on npm there is still v1.2.0 from a month ago.

**Comment by alexanderVu** [comment]
Yes I will do. The bug is primary in the documentation. The scalar types was missing, in the base/primary `gql` typeDef. Thats all. But I also find several other bugs in 'apollo-server-koa' package. Actually I switch to pure 'apollo-server' implementation.
